### ISSUE TITLE
Build failure on Linux

### ISSUE THREAD

**Issue by Earnestly** [Duncaen/OpenDoas#10]
* `gcc 6.1.1`
* `glibc 2.24`

Using `./configure --prefix=/usr` and `make COPTS=-Wno-error` ([Why?](https://github.com/Duncaen/OpenDoas/issues/9)) (I've also removed `-flto` from `CFLAGS` and `LDFLAGS` for a slightly better error message.)

```
[...SNIP...]
ar: creating libopenbsd.a
In file included from /usr/include/stdio.h:938:0,
                 from env.c:22:
/usr/include/bits/stdio2.h: In function ‘sprintf’:
/usr/include/bits/stdio2.h:33:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘snprintf’:
/usr/include/bits/stdio2.h:64:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘fprintf’:
/usr/include/bits/stdio2.h:97:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __fprintf_chk (__stream, __USE_FORTIFY_LEVEL - 1, __fmt,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __va_arg_pack ());
    ~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘printf’:
/usr/include/bits/stdio2.h:104:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘dprintf’:
/usr/include/bits/stdio2.h:141:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __dprintf_chk (__fd, __USE_FORTIFY_LEVEL - 1, __fmt,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    __va_arg_pack ());
    ~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘asprintf’:
/usr/include/bits/stdio2.h:178:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __asprintf_chk (__ptr, __USE_FORTIFY_LEVEL - 1, __fmt,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     __va_arg_pack ());
     ~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘__asprintf’:
/usr/include/bits/stdio2.h:186:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __asprintf_chk (__ptr, __USE_FORTIFY_LEVEL - 1, __fmt,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     __va_arg_pack ());
     ~~~~~~~~~~~~~~~~~
/usr/include/bits/stdio2.h: In function ‘obstack_printf’:
/usr/include/bits/stdio2.h:194:10: error: invalid use of ‘__builtin_va_arg_pack ()’
   return __obstack_printf_chk (__obstack, __USE_FORTIFY_LEVEL - 1, __fmt,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           __va_arg_pack ());
           ~~~~~~~~~~~~~~~~~
make: *** [<builtin>: env.o] Error 1
make: *** Waiting for unfinished jobs....
rm parse.c
```

**Comment by Duncaen** [comment]
Hi, thanks for your report, I tried it today with gcc 6.2.0.

I think actually the problem was the configure script, it used clang as default if `$CC` isn't set and therefor none of the checks worked.
Would be nice if you can give the `OPENBSD_6_0` branch a try.

Cheers,

**Comment by Earnestly** [comment]
Can confirm that `OPENBSD_6_0` builds without issue here (still using `COPTS=-Wno-error`).

**Comment by Duncaen** [comment]
Tagged a new release, it should build fine with `-Werror` and `gcc-6.2.0` too.
