### ISSUE TITLE
A few werror issues

### ISSUE THREAD

**Issue by Earnestly** [Duncaen/OpenDoas#9]
* `gcc 6.1.1`
* `glibc 2.24`

Normally I'd just turn off `-Werror` but felt you should probably know about these issues since you're including it by default.

Environments:
* `CPPFLAGS="-D_FORTIFY_SOURCE=2"`
* `CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto"`
* `LDFLAGS="-flto -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"`

Building with `./configure --prefix=/usr` and running `make`.

```
Checking for explicit_bzero ...		no.
Checking for strlcat ...   		no.
Checking for strlcpy ...   		no.
Checking for errc ...      		no.
Checking for verrc ...     		no.
Checking for setprogname ...		no.
Checking for readpassphrase ...		no.
Checking for strtonum ...  		no.
Checking for reallocarray ...		no.
Checking for bsd_auth_h ...		no.
Checking for pam_appl_h ...		no.
Checking for shadow_h ...  		no.
Checking for execvpe ...   		no.
Checking for setresuid ... 		no.
Checking for pledge ...    		no.
Checking for __attribute__ ...		no.
yacc  parse.y 
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o doas.o doas.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o env.o env.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/explicit_bzero.o libopenbsd/explicit_bzero.c
mv -f y.tab.c parse.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/strlcat.o libopenbsd/strlcat.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/strlcpy.o libopenbsd/strlcpy.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/errc.o libopenbsd/errc.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/verrc.o libopenbsd/verrc.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/progname.o libopenbsd/progname.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/readpassphrase.o libopenbsd/readpassphrase.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/strtonum.o libopenbsd/strtonum.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/reallocarray.o libopenbsd/reallocarray.c
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fstack-check -flto -g -fvar-tracking-assignments -I. -I./libopenbsd -Wall -Wextra -Werror -pedantic -std=c11 -MD -MP -Wno-unused-result -DVERSION="\"0.3.2\"" -D__linux__ -D_DEFAULT_SOURCE -D_GNU_SOURCE -DUID_MAX=60000 -DGID_MAX=60000 -DNO_ATTRIBUTE_ON_RETURN_TYPE=1 -D_FORTIFY_SOURCE=2  -c -o libopenbsd/execvpe.o libopenbsd/execvpe.c
In file included from env.c:19:0:
env.c:47:20: error: ‘envtree_RB_PREV’ defined but not used [-Werror=unused-function]
 RB_GENERATE_STATIC(envtree, envnode, node, envcmp)
                    ^
./libopenbsd/sys-tree.h:687:1: note: in definition of macro ‘RB_GENERATE_INTERNAL’
 name##_RB_PREV(struct type *elm)     \
 ^~~~
env.c:47:1: note: in expansion of macro ‘RB_GENERATE_STATIC’
 RB_GENERATE_STATIC(envtree, envnode, node, envcmp)
 ^~~~~~~~~~~~~~~~~~
env.c:47:20: error: ‘envtree_RB_NFIND’ defined but not used [-Werror=unused-function]
 RB_GENERATE_STATIC(envtree, envnode, node, envcmp)
                    ^
./libopenbsd/sys-tree.h:644:1: note: in definition of macro ‘RB_GENERATE_INTERNAL’
 name##_RB_NFIND(struct name *head, struct type *elm)   \
 ^~~~
env.c:47:1: note: in expansion of macro ‘RB_GENERATE_STATIC’
 RB_GENERATE_STATIC(envtree, envnode, node, envcmp)
 ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: env.o] Error 1
make: *** Waiting for unfinished jobs....
doas.c: In function ‘main’:
doas.c:238:6: error: variable ‘nflag’ set but not used [-Werror=unused-but-set-variable]
  int nflag = 0;
      ^~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: doas.o] Error 1
libopenbsd/execvpe.c: In function ‘execvpe’:
libopenbsd/execvpe.c:58:5: error: nonnull argument ‘name’ compared to NULL [-Werror=nonnull-compare]
  if (name == NULL || *name == '\0') {
     ^
cc1: all warnings being treated as errors
make: *** [<builtin>: libopenbsd/execvpe.o] Error 1
rm parse.c
```

I'd claim a lot of these warnings are a bit too pendantic, such as `non-null` comparisons, but such is gcc these days.

**Comment by Duncaen** [comment]
```
doas.c:238:6: error: variable ‘nflag’ set but not used [-Werror=unused-but-set-variable]
  int nflag = 0;
      ^~~~~
```
This is because `configure` can't find the PAM or shadow headers, in this case it can't do any password verification and only allows rules with `nopass` which is basically the same as `-n`.
I think, I should remove this codepath and exit in configure if it can't find any password authentication method.

The `CFLAGS` come from OpenBSD, and `-Werror` works fine with `gcc-4.9.4` and `clang-3.8.1`.
`env.c` comes from OpenBSD too without any changes.

I have to get a newer gcc and look into it in the next few days, I plan to sync it with upstream and then create tags matching OpenBSD releaes, currently the code sticks to `OpenBSD-current`.

**Comment by Earnestly** [comment]
AFAIK gcc 6.1.1 changed a few things to detect a lot more pendantic warnings (not `-Wpedantic`) which generally just makes `-Werror` less useful.  The `non-null` one is pretty common.
